
# This file was *autogenerated* from the file ./3_3_7.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_13 = Integer(13); _sage_const_11 = Integer(11); _sage_const_16 = Integer(16)#!/usr/local/bin/sage

x = var('x')
###################################
# problem 3.3.7
#x_val = [-0.1, 0, 0.2, 0.3]
#y_val = [5.3, 2, 3.19, 1]

#x_val = [-0.1, 0, 0.2, 0.3, 0.35]
#y_val = [5.3, 2, 3.19, 1, 0.97260]
###################################

################################
# problem 3.3 10
x_val = [-_sage_const_2 , -_sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_2 , _sage_const_3 ]
y_val = [_sage_const_1 , _sage_const_4 , _sage_const_11 , _sage_const_16 , _sage_const_13 , -_sage_const_4 ]
################################

iter = _sage_const_1 
buf_1 = y_val
buf_2 = []
res = []

while len(buf_1) > _sage_const_0 :
  print buf_1
  buf_2 = []
  res += [buf_1[_sage_const_0 ]]
  for i in xrange(len(buf_1) - _sage_const_1 ):
    buf_2 += [(buf_1[i+_sage_const_1 ] - buf_1[i])/(x_val[i+iter] - x_val[i])]
  iter += _sage_const_1 
  buf_1 = buf_2

print "-----------------------------"
print res


