
# This file was *autogenerated* from the file ./2_2_6.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10)#!/usr/local/bin/sage

def fixed_iter(g, v, tol, num):
  try:
    g = g._fast_float_(g.variables()[_sage_const_0 ])
  except AttributeError:
    pass
  print "iter :", num
  print "v :", v
  print "g v :", g(v)
  print "precision :", g(v) - v
  if num == _sage_const_10 :
    return g(v)
  if abs(g(v) - v) < tol:
    return g(v)
  else:
    return fixed_iter(g, g(v), tol, num+_sage_const_1 )

x = var('x')
#f = (x^4) - 3*(x^2) - 3
#g = x - f
#g = ((1/3)*(x^4) - 3)^(1/2)
g = (_sage_const_3 *(x**_sage_const_2 ) + _sage_const_3 )**(_sage_const_1 /_sage_const_4 )
fixed_iter(g, _sage_const_1 , _sage_const_10 **(-_sage_const_2 ), _sage_const_0 )


