
# This file was *autogenerated* from the file ./4_4_7.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0p0 = RealNumber('0.0'); _sage_const_4 = Integer(4); _sage_const_0p25 = RealNumber('0.25')#!/usr/local/bin/sage

h = _sage_const_0p25 
a = _sage_const_0 
b = _sage_const_2 
n = (b - a) / h

x = var('x')

f = (x ** _sage_const_2 ) * ln(x**_sage_const_2  + _sage_const_1 )

# composite trapezoidal rule
# just sum of trapezoidal rule
res = _sage_const_0p0 
for i in xrange(n):
  res += (h / _sage_const_2 ) * (f(a + i * h) + f(a + (i + _sage_const_1 ) * h))
print res

# composite simpson's rule
# just sum of simpson's rule
res = _sage_const_0p0 
for i in xrange(_sage_const_0 , n, _sage_const_2 ):
  res += (h / _sage_const_3 ) * (f(a + i * h) + _sage_const_4  * f(a + (i + _sage_const_1 ) * h) + f(a + (i + _sage_const_2 ) * h))
print res

# compoisite midpoint rule
res = _sage_const_0p0 
for i in xrange(_sage_const_0 , n, _sage_const_2 ):
  res += _sage_const_2  * h * (f(a + (i + _sage_const_1 ) * h))
print res


