
# This file was *autogenerated* from the file ./2_5_1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0p5 = RealNumber('0.5'); _sage_const_5 = Integer(5)#!/usr/local/bin/sage

def aitken_method(f, v, num):
  nv = f(v)
  nnv = f(f(v))
  vhat = v - ((nv - v)**_sage_const_2 )/(nnv - _sage_const_2 *nv + v)
  print "iter :", num
  print "p hat :", vhat
  
  if num > _sage_const_5 :
    return vhat
  else:
    return aitken_method(f, nv, num + _sage_const_1 )

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

x = var('x')

f = cos(x)
res = aitken_method(f, _sage_const_0p5 , _sage_const_1 )
print "--------------------------------"
f = _sage_const_3 **(-x)
res = aitken_method(f, _sage_const_0p5 , _sage_const_1 )


